version: "3"

services:
  api:
    image: cosmtrek/air
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - PORT=4000
      - RAPID_API_BASE_URL=${RAPID_API_BASE_URL}
      - RAPID_API_KEY=${RAPID_API_KEY}
      - RAPID_API_HOST=${RAPID_API_HOST}
    ports:
      - "4000:4000"
    volumes:
      - .:/go/src/app
    command: air
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
